ONLYOFFICE-QA/onlyoffice_webdriver_wrapper

lib/onlyoffice_webdriver_wrapper/helpers/headless_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/real_display_tools.rb
Check if platform is not mac
Cannot use headless on mac see:
https://github.com/leonid-shevtsov/headless/issues/31#issuecomment-8933108
Drop support of low resolution display, srew them.
=> Minor refactor of starting headless session

lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/real_display_tools.rb
```
Failed to get size of gamma for output screenScreen 0: minimum 1 x 1, current 1681 x 1051, maximum 1681 x 1051screen connected 1681x1051+0+0 0mm x 0mm 1681x1051 0.00*
09:46:18/28.11.16 [real_display_tools] Real Display Exists: true
```
But real display cannot exist on this pc.
So need to check for "Failed` line and create display in such case.
=> Sometimes on nct-at docker there is such result of xrandr

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb
Should send driver path as option to WebDriver
Since webdriver 3.0.3
See:
https://github.com/SeleniumHQ/selenium/pull/3158
=> Setting driver path will be deprected

lib/onlyoffice_webdriver_wrapper/webdriver.rb, lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_type_helper.rb
Calls for `driver.mouse` cause deprecated warning like this:
```
WARN Selenium [DEPRECATION] Driver#mouse is deprecated with w3c
implementation. Instead use driver.action..perform
```
Fix #55
=> Remove deprecated calls for `@driver.mouse`

lib/onlyoffice_webdriver_wrapper/amazon_s3_wrapper.rb, spec/amazon_s3_wrapper_spec.rb
because if file array is empty - method try to delete first of it(it is a path to folder, no filename)
=> Add check for get_files_by_prefix

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb, onlyoffice_webdriver_wrapper.gemspec
```
3.4.3 (2017-06-16)
==================
Ruby:
* Fixed a regression when passing symbol as :desired_capabilities caused NoMethodError (issue 4187).
3.4.2 (2017-06-14)
==================
Ruby:
* Added unhandledPromptBehavior to the list of known capabilities.
* Added timeouts to the list of known capabilities.
* Fixed a regression when passing hash as :desired_capabilities caused NoMethodError (issue 4172, thanks Thomas Walpole).
* Fixed a regression when extension capabilities (the ones that have ":" inside)
were filtered out when doing protocol handshake.
* Improved handling of capability names passed as plain camelCased strings
vs Rubyish snake_cased symbols when doing protocol handshake.
Chrome:
* Fixed a regression when passing :switches to driver initialization was ignored.
3.4.1 …
```
=> Update to webdriver 3.4.3

onlyoffice_webdriver_wrapper.gemspec
Changes:
```
3.6.0 (2017-09-25)
==================
Edge:
* Fixed a bug when execute_script failed using server + Edge (issue #4651)
Firefox:
* Fixed a bug when web extension failed to install using profile class (issue #4093)
PhantomJS:
* Support is deprecated in favor of headless Chrome/Firefox or HTMLUnit.
PhantomJS is no longer actively developed, and support will eventually
be dropped.
```
=> Update webdriver to 3.6.0

spec/html_examples/javascript_error.html, spec/webdriver_spec.rb
On some pc there is no error on 127.0.0.1 page (possible
reason in firewall, but is not important)
Explicitly open page with js error
=> Redone test for checking console error

Changelog.md, lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb, lib/onlyoffice_webdriver_wrapper/webdriver.rb
Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#84
This broke starting web driver because of `ip_of_remove_server`
=> Revert "Support of `Webdriver#proxy`"

onlyoffice_webdriver_wrapper.gemspec
Changes are:
```
3.12.0 (2018-05-08)
===================
Ruby:
* Added User-Agent header to requests from Selenium to give remote
ends more visibility into distribution of clients (thanks @sah)
* Added Selenium::WebDriver::VERSION constant (thanks @sah)
* Added changelog link to RubyGems page
* Fixed a bug when requests were sent with empty Content-Type,
which should instead be application/json (issue #5615 and #5659)
* Fixed a bug when failed connection attempt was retried without
grace period for remote to resolve its problem (thanks @amckinley42)
* Fixed a bug with accidentally removed HasNetworkConnection driver extension
Chrome:
* Fixed a bug when deprecation message for using Chrome extensions
was incorrectly shown (thanks @treby)
Safari:
* Added support getting permissions via …
```
=> Update `selenium-webdriver` to 3.12.0

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
It will allow run chrome as root user, accroding to:
https://blog.phusion.nl/2018/05/24/using-chrome-headless-selenium-and-capybara-inside-gitlab-runner-and-docker/
=> Add `--no-sandbox` flag to running chrome

spec/webdriver_spec.rb
Current 2.35 chromedriver has troubles with reading url in iframe
Changes are:
```
----------ChromeDriver v2.39 (2018-05-30)----------
Supports Chrome v66-68
Resolved issue 2436: ChromeDriver for Android does not provide useful error message for old adb version [[Pri-1]]
Resolved issue 2431: ChromeDriver tests that close Windows are flaky [[Pri-1]]
Resolved issue 2259: Click on component into an Iframe (with container padding > 0) is not working [[Pri-1]]
Resolved issue 2161: ChromeDriver remote debug port reservation race conditions [[Pri-2]]
Resolved issue 2420: Get Alert Text is not returning spec compliant error codes [[Pri-2]]
Resolved issue 2369: Clean up state of androidUseRunningApp feature [[Pri-2]]
Resolved issue 2406: Minimize/Maximize window need a w3c compliant endpoints …
```
=> Update chromedrvier to latest release 2.39

Changelog.md
Changes are here:
https://github.com/mozilla/geckodriver/releases
=> Update geckodriver from 0.18 to 0.20.1

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
Don't know reason but using chrome 70 with this flag cause
`failed to change window state to normal, current state is maximized`
error on `driver.manage.window.size = Selenium::WebDriver::Dimension.new`
After flag removed maximize chrome on real display by
`driver.manage.window.maximize` and maximize in `xvfb` by setting
specific size, since xvfb not support maximize
=> Remove `--start-maximized` flag for running chrome

Changelog.md
Changes at:
https://github.com/mozilla/geckodriver/releases
Fix issue with starting firefox in travis
=> Update `geckodriver` from 0.20.1 to 0.23.0

Changelog.md
Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#103
Seems upgrade of chromedriver cause password filled in User field in login to onlyoffice
See https://qa-tcm.teamlab.info/testrail/index.php?/runs/view/870196&group_by=cases:section_id&group_order=asc
=> Revert "Update `chromedriver` to 2.43"

spec/webdriver_download_spec.rb
webdriver already quit, no need to call afterwards
=> Fix test for download dir

lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_alert_helper.rb
Since:
https://github.com/SeleniumHQ/selenium/commit/6f6af6e8e5d4dbebac45b9d185ee4326d0cb8072
=> Remove deprecated `NoAlertOpenError`

Changelog.md, lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
Seems flag was changed in some Chrome updates.
I'm not sure, but seems until Chrome 77 old
flag was working fine. But after update is not.
See:
https://stackoverflow.com/a/33152235/820501
=> Fix downloading multiple files in Chrome

.travis.yml
See:
https://travis-ci.community/t/the-following-packages-cannot-be-authenticated-google-chrome-stable/6866/2
https://docs.travis-ci.com/user/chrome#selecting-a-chrome-version
Old variant cause `unauthenticated` errors:
https://travis-ci.org/onlyoffice-testing-robot/onlyoffice_webdriver_wrapper/jobs/641257617?utm_medium=notification&utm_source=github_status
=> Redone chrome install syntax according to docs

Changelog.md
Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#169
Problems in `ONLYOFFICE/testing-documentserver` project
Methods like:
` user.doc_editor.text_commands.press_button([:control, 'c'])`
type `c` character in Canvas instead of copiying.
But seems Chrome 80 work correct with chromedriver 79, so revert chromedriver, but do not downgrade Chrome
=> Revert "Update `chromedriver` to 80.0.3987.16"

Changelog.md, lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_helper.rb
This error started happened for DocumentServer with test example
Don't know actual reason
File downloading by link manually is good, but this command is failing
with something like this:
```
Encoding::UndefinedConversionError:
"\xE2"
```
=> Fix `Encoding::UndefinedConversionError` for `Webdriver#download`

Changelog.md, lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/real_display_tools.rb
I haven't found any case that xrandr is raise exception in that
code. Search 5GB achieve of `wrata-staging` history.
Not a single log hist
=> Remove `xrandr` exception handling

Changelog.md, lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb, lib/onlyoffice_webdriver_wrapper/webdriver.rb
This feature is last used a very long time ago
In current state it'll be easier to implement remote selenium
server support from ground up, rather than trying to make
this feature working again in current code base
=> Remove support of `ip_of_remote_server`

.rubocop.yml, CHANGELOG.md, lib/onlyoffice_webdriver_wrapper/helpers/headless_helper.rb, lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/headless_screenshot_patch.rb, onlyoffice_webdriver_wrapper.gemspec, spec/onlyoffice_webdriver_wrapper/headless_helper_spec.rb
This problem is fixed on master of gem
Since:
https://github.com/leonid-shevtsov/headless/pull/98
But there was no release for 4 years, not sure how long to wait
Currently just monkey-patch solution from upstream
=> Fix problem with taking headless screenshot

CHANGELOG.md, lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
In current version of Chrome this seems to do
nothing
=> Remove `w3c: false` for Chrome start options

CHANGELOG.md, lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_helper.rb
Old variant generates warning
```
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
=> Replace usage of `Kernel.open` to `URI#read`

CHANGELOG.md, lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
Do not know the reason, but seems without this option Chrome 92
are failing to start with
```
X connection error received
```
in chromedriver logs
Don't know why but hope this helps
=> Force `-disable-gpu` for `chromedriver`

CHANGELOG.md
Remove Chromedriver `92.0.4515.43`
Cannot update to 
Because [this test](https://github.com/ONLYOFFICE-QA/onlyoffice_webdriver_wrapper/blob/faa8ab43a2b6021a8bd660cea345355a75a386fb/spec/type_helper_spec.rb#L35) is failing on 98 with incorrect symbol send instead of shift+left
=> Add Chromedriver `97.0.4692.71`

CHANGELOG.md, onlyoffice_webdriver_wrapper.gemspec
The warning is:
```
WARNING:  License identifier 'AGPL-3.0' is deprecated. Use an identifier from
https://spdx.org/licenses or 'Nonstandard' for a nonstandard license,
or set it to nil if you don't want to specify a license.
Did you mean 'AFL-3.0', 'APL-1.0'?
```
=> Fix `gem` license name warning

CHANGELOG.md, onlyoffice_webdriver_wrapper.gemspec
Warning is like:
```
WARNING:  You have specified the uri:
https://github.com/ONLYOFFICE-QA/onlyoffice_webdriver_wrapper
for all of the following keys:
homepage_uri
source_code_uri
Only the first one will be shown on rubygems.org
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
```
=> Fix `gem build` warning related to duplicate metadata

.github/workflows/ruby.yml, CHANGELOG.md
Default GitHub Actions updated from Ubuntu 22.04 to Ubuntu 24.04
Ubuntu 24 includes `imagemagick` by default:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
Ubuntu 24 is not:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
Notice about rollout: https://github.com/actions/runner-images/issues/10636
=> Fix running CI on `ubuntu-latest` which is Ubuntu 24 now
