lib/onlyoffice_webdriver_wrapper/webdriver.rb
onlyoffice_webdriver_wrapper.gemspec

Fix problem with
`Selenium::WebDriver::Chrome::Service.executable_path`
See SeleniumHQ/selenium#2919

Ability to use Webdriver 3.0

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_helper.rb
onlyoffice_webdriver_wrapper.gemspec

It was push to `selenium-webdriver` gem since version 3.0.0
See
https://github.com/SeleniumHQ/selenium/commit/2bb9c0b9f2d9da3050f16fa7b7bbbdcfef23021a

Remove workaround for bug with not rounded coordinates

---

lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/real_display_tools.rb

xrandr stderr should be in stdout

---

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb

Popup asking to save password will not be shown

Disable chrome password manager

---

lib/onlyoffice_webdriver_wrapper/helpers/headless_helper.rb
lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/process_helper.rb

To detemine if processes are killed

Add temp ability to show all processes on server

---

onlyoffice_webdriver_wrapper.gemspec

Update webdriver for 3.0.3 version

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb

Test still failed, but took a lot of time for it.
Need to find real reason behind it.

Seems that big start timeout didn't do any good

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb

Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#25
No,test begin failing more ofter

Revert "Seems that big start timeout didn't do any good"

---

lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_extension.rb

May help fix TimeOutError problem, if not - should remove at all.

Increase timeouts for start\stop

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb

see http://stackoverflow.com/questions/20414729/webdriver-wait-for-jquery-to-finish 
for window.jquery purposes

Add 3 retries for stale element error and JQuery status check

---

onlyoffice_webdriver_wrapper.gemspec

Bump `selenium-webdriver` to 3.0.4

---

lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb

Fix #39
Also see
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015

Do not show password manager bubble in chrome

---

onlyoffice_webdriver_wrapper.gemspec

Update geckodriver to 0.15
And webdriver to 3.3.0

Fix problem with running firefox

---

lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb

Fixed in webdriver 3.0.4
See:
https://github.com/SeleniumHQ/selenium/pull/3174

Support profiles of firefox for geckodriver

---

.travis.yml
onlyoffice_webdriver_wrapper.gemspec
spec/webdriver_firefox_spec.rb

selenium webdriver:
chromedriver:
https://chromedriver.storage.googleapis.com/2.29/notes.txt
geckodriver:
https://github.com/mozilla/geckodriver/blob/master/CHANGES.md

Update selenium-webdriver, geckodriver, chromedriver to most recent stable of 15.05.2017

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_js_methods.rb

Add logs to `execute_javascript`

---

lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb

Latest release of September 2017

Update geckodriver to 0.18

---

onlyoffice_webdriver_wrapper.gemspec

Update webdriver from 3.4.3 to 3.5.2

---

lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_screenshot_helper.rb

Since /mnt/data_share is turned off

Change screenshot folder location to local

---

onlyoffice_webdriver_wrapper.gemspec

Update `selenium-webdriver` to current actual release

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb
lib/onlyoffice_webdriver_wrapper/helpers/firefox_helper.rb
lib/onlyoffice_webdriver_wrapper/webdriver.rb

Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#85

Revert "Revert "Support of `Webdriver#proxy`""

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/webdriver.rb
spec/webdriver_firefox_spec.rb

In `@driver.action.move_to` calls

Fix non-integer coordinates

---

onlyoffice_webdriver_wrapper.gemspec

Update selenium-webdriver to 3.14.0

---

Changelog.md
onlyoffice_webdriver_wrapper.gemspec

Update `selenium-webdriver` gem to 3.14.1

---

Changelog.md

Changes are:
```
----------ChromeDriver v2.43 (2018-10-16)----------
Supports Chrome v69-71
Resolved issue 2537: Parsing of proxy configuration is not standard compliant [[Pri-1]]
Resolved issue 2607: Launch App command is flaky [[Pri-2]]
Resolved issue 2575: Screenshot of element inside iFrame is taken incorrectly [[Pri-2]]
Resolved issue 1855: Feature request : ChromeDriver to support window resizing over a remote connection [[Pri-2]]
Resolved issue 1998: Error codes are not handled in Clear element [[Pri-2]]
Resolved issue 2016: Not Waiting until element is visible [[Pri-2]]
Resolved issue 1936: Get element property is not implemented [[Pri-2]]
Resolved issue 1992: Switch To Frame is not spec compliant [[Pri-2]]
Resolved issue 2001: Execute Async Script does not return spec compliant …
```

Update `chromedriver` to 2.43

---

spec/type_to_locator_spec.rb

This will be usefull in checking focus problem
after update to chromedriver 2.43

Add simple test for type_to_locator

---

Changelog.md
spec/type_to_locator_spec.rb

Reverts onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#106
Need to investigate problem with login to teamlab

Revert "Revert "Update `chromedriver` to 2.43""

---

.rspec

Simplify debug of problem on travis

Ouput test name while running test

---

onlyoffice_webdriver_wrapper.gemspec

Changes at:
https://github.com/SeleniumHQ/selenium/commit/cb45dc1afeb7aa3b6f63bc186750ad6b07ceed12

Actualize webdriver gem to 3.141.0

---

lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_tab_helper.rb

Probably will fix some test with `Net::ReadTimeout` error

Increase timeout for wait page to load

---

Changelog.md

Without it latest Chrome 74 will fail to start
Changes are:
```
----------ChromeDriver v74.0.3729.6 (2019-03-14)----------
Supports Chrome v74
Resolved issue 2799: Recent change to WebDriver Tests causes ChromeDriver to fail W3C Tests [[Pri-]]
Resolved issue 2798: GET /sessions is not working if at least one of the sessions is in W3C mode [[Pri-3]]
Resolved issue 2783: Improper UTF-8 encoding for CSS child selectors (driver.page_source) [[Pri-]]
Resolved issue 2782: ChromeDriver can't connect to Chrome when /dev/shm is not available on Linux [[Pri-2]]
Resolved issue 2773: Raise a standard exception when element is overlay by another element [[Pri-2]]
Resolved issue 2768: 2.46 produces unexpected debug.log file if verbose logging is enabled [[Pri-1]]
Resolved issue 2749: Update Switch To …
```

Update ChromeDriver to 74.0.3729.6

---

.rubocop_todo.yml
Changelog.md
lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb

Changes are:
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt
May fix problem with starting several chromes and error
about to slow connection, but maybe not.

Update chromedriver to 75

---

lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_alert_helper.rb

Do not handle exception, but check if alert exists

Change logick for checking for alert in `alert_confirm`

---

Changelog.md

Changes at:
https://github.com/mozilla/geckodriver/releases/tag/v0.24.0

Update `geckodriver` from 0.23.0 to 0.24.0

---

Changelog.md

Changes are:
https://chromedriver.storage.googleapis.com/77.0.3865.40/notes.txt

Actualize Chromedriver to 77.0.3865.40

---

.travis.yml

See:
https://docs.travis-ci.com/user/reference/xenial/#third-party-apt-repositories-removed
Actual for xenail

Use actual syntax for install google chrome

---

onlyoffice_webdriver_wrapper.gemspec

Currently just for test, but may work

Remove strict restriction of `page-object`

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/webdriver.rb

In consistency with changes at
https://github.com/ONLYOFFICE/testing-onlyoffice/pull/1666
After update watir at:
https://github.com/onlyoffice-testing-robot/onlyoffice_webdriver_wrapper/pull/139
Fix #152

Replace all `visible?` usage to `present?`

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/version.rb

Also fix incorrect changes in readme

Bump version to v0.1.1

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_attributes_helper.rb

Last usage remove at:
https://github.com/ONLYOFFICE/testing-onlyoffice/pull/1866

Remove `Webdriver#get_element_by_parameter`

---

spec/webdriver_firefox_spec.rb

Actualize file url for test

---

spec/type_to_locator_spec.rb

It'll fail after update to chromedriver 80

Add test for checking type to locator with control

---

lib/onlyoffice_webdriver_wrapper/webdriver.rb
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_js_methods.rb
spec/webdriver_js_methods_spec.rb

Move `remove_element` to `WebdriverJsMethods`

Add test for `remove_element`

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/webdriver.rb
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_js_methods.rb
spec/webdriver_js_methods_spec.rb

Old version only works with jquery
New one work without it and possible to work with jQuery

Rename and redone `jquery_selector_by_xpath` to `dom_element_by_xpath`

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb

I don't think this is a good code pattern and may introduce more
troubles or hide real problem which should be fixed

Do not try to start selenium once more

---

Changelog.md
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_type_helper.rb
spec/type_to_locator_spec.rb

See:
https://github.com/SeleniumHQ/selenium/issues/8044

Add workaround for Webdriver bug with chrome typing with :control

---

CHANGELOG.md
lib/onlyoffice_webdriver_wrapper/webdriver/webdriver_style_helper.rb
spec/html_examples/set_style_show_by_xpath.html
spec/onlyoffice_webdriver_wrapper/web_driver_set_style_show_by_xpath_spec.rb

Simplified by using `dom_element_by_xpath`

Simplify `WebDriver#set_style_show_by_xpath` 

---

CHANGELOG.md
onlyoffice_webdriver_wrapper.gemspec

To correct update via Dependabot

Freeze exact version of gem dependencies

---

.rubocop.yml
.travis.yml
CHANGELOG.md
onlyoffice_webdriver_wrapper.gemspec

Drop ruby < 2.5

---

CHANGELOG.md
Gemfile.lock
lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper/chrome_version_helper.rb
lib/onlyoffice_webdriver_wrapper/version.rb

Fix failure with incorrect `chromedriver` bin location

Release v0.8.1

---

CHANGELOG.md
Gemfile.lock
lib/onlyoffice_webdriver_wrapper/version.rb

* Add Chromedriver `90.0.4430.24`
* Remove Chromedriver 87 and 88

Release v0.13.0

---

CHANGELOG.md
lib/onlyoffice_webdriver_wrapper/webdriver.rb
spec/onlyoffice_webdriver_wrapper/web_driver_open_spec.rb

Remove extra refresh if `WebDriver#open` failed

Add more details in `WebDriver#open` error

---

CHANGELOG.md

Remove chromedriver for Chrome 90

Add Chromedriver `94.0.4606.41`

---

CHANGELOG.md

Add Chromedriver `101.0.4951.15`

---

CHANGELOG.md

Remove Chromedriver `101.0.4951.15`

Add chromedriver `104.0.5112.29`

---

CHANGELOG.md

Changes at [here](https://github.com/mozilla/geckodriver/releases/tag/v0.31.0)

Update `geckodriver` from `v0.30.0` to `v0.31.0`

---

CHANGELOG.md
README.md
Rakefile

Update geckodriver to v0.34.0 and add script to update it
